sudo: required

services:
  - docker

language: generic

script:
  - docker login -u="$YOTPO_REGISTRY_USER" -p="$YOTPO_REGISTRY_PASSWORD" registry.yotpo.com
  - pip install --user awscli
  - eval $(aws ecr get-login --region us-east-1)

  - docker build -t hive-front starbook-front
  - docker tag hive-front registry.yotpo.com/hive-front:"$TRAVIS_COMMIT"
  - docker tag hive-front 402837048690.dkr.ecr.us-east-1.amazonaws.com/hive-front:"$TRAVIS_COMMIT"

  - docker build -t hive-back starbook-backend
  - docker tag hive-back registry.yotpo.com/hive-back:"$TRAVIS_COMMIT"
  - docker tag hive-back 402837048690.dkr.ecr.us-east-1.amazonaws.com/hive-back:"$TRAVIS_COMMIT"

  - docker images | grep hive

  - # docker push 402837048690.dkr.ecr.us-east-1.amazonaws.com/hive-front:"$TRAVIS_COMMIT"
  - # docker push 402837048690.dkr.ecr.us-east-1.amazonaws.com/hive-back:"$TRAVIS_COMMIT"
  - docker push registry.yotpo.com/hive-front:"$TRAVIS_COMMIT"
  - docker push registry.yotpo.com/hive-back:"$TRAVIS_COMMIT"
