sudo: required
dist: trusty
language: generic
services:
  - docker
env:
  global:
  - PROJECT="hive"
  - BUILD_DATE=$(date +"%Y-%m-%d_%H-%M-%S")
before_install:
- mkdir $HOME/bin
- export PATH=$PATH:$HOME/bin
- wget https://s3.amazonaws.com/ops-yotpo/public/docker/ecr-login-helper/docker-credential-ecr-login -O $HOME/bin/docker-credential-ecr-login
- chmod +x $HOME/bin/docker-credential-ecr-login
- mkdir -p ~/.docker/
- wget https://s3.amazonaws.com/ops-yotpo/public/docker/ecr-login-helper/config.json -O ~/.docker/config.json
script:
  - docker build -t 402837048690.dkr.ecr.us-east-1.amazonaws.com/${PROJECT}/front:${TRAVIS_COMMIT} -f Dockerfile.front.prod .
  - docker build -t 402837048690.dkr.ecr.us-east-1.amazonaws.com/${PROJECT}/back:${TRAVIS_COMMIT} starbook-backend
after_success:
  - "./.travis/after_success.sh"
