version: '2'

networks:
  hive:
    ipam:
      driver: default
      config:
      - subnet: 172.35.0.0/16
        ip_range: 172.35.5.0/24
        gateway: 172.35.0.1

services:
  hive-server:
    build: hive
    image: hive
    ports:
      - "5000:5000"
    env_file:
      - hive/hive-server-example.env
    links:
      - elasticsearch
    networks:
      - hive

  elasticsearch:
    image: elasticsearch:2.3
    ports:
      - "9200:9200"
    networks:
      - hive

  kibana:
    image: kibana:4.5.2
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - hive

  logstash:
    image: logstash
    build: logstash
    links:
      - elasticsearch
    volumes:
      - ./logstash:/config-dir
    ports:
      - 5678:5678
    networks:
      - hive
