version: '2'

networks:
  starbook:
    ipam:
      driver: default
      config:
      - subnet: 172.35.0.0/16
        ip_range: 172.35.5.0/24
        gateway: 172.35.0.1

services:
  starbook-backend:
    build: starbook-backend
    image: starbook-backend
    ports:
      - "5000:5000"
    env_file:
      - starbook-backend/starbook-backend-example.env
    links:
      - elasticsearch
      - redis
    networks:
      - starbook

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - starbook

  elasticsearch:
    image: elasticsearch:2.3
    ports:
      - "9200:9200"
    networks:
      - starbook

  # slackbot:
  #   build: slackbot
  #   links:
  #     - starbook-backend
  #   env_file:
  #     - slackbot/slackbot-example.env

  starbook-front:
    build:
      context: starbook-front
      dockerfile: Dockerfile.local
    image: starbook-front
    env_file:
      - starbook-front/starbook-front-example.env
    ports:
      - "8080:8080"
    volumes:
      - ./starbook-front/env:/var/www/env/
    networks:
      - starbook

  kibana:
    image: kibana:4.5.2
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - starbook

  logstash:
    image: logstash
    build: logstash
    links:
      - elasticsearch
    volumes:
      - ./logstash:/config-dir
    ports:
      - 5678:5678
    networks:
      - starbook
